---
- name: create ~/app directory
  file:
    path: /app
    state: directory

- name: copy file onto server
  copy:
    src: artifact.tar.gz
    dest: "/app/artifact.tar.gz"

- name: extract tar file
  shell: tar -xvf /app/artifact.tar.gz

- name: move extracted files to /app
  shell: mv backend /app

- name: (re)start app
  shell: |
    echo "TYPEORM_PORT = $TYPEORM_PORT"
    echo "TYPEORM_ENTITIES = $TYPEORM_ENTITIES"
    cd /app/backend
    npm i -s
    pm2 stop default || echo "No pm2 process to stop"
    pm2 -s start npm -- start
  register: result

- name: print message
  debug:
    msg: "{{ result.stdout_lines }}"
#  environment:
#    ENVIRONMENT: production
#    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION')}}"
#    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES')}}"
#    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST')}}"
#    TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT')}}"
#    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME')}}"
#    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD')}}"
#    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE')}}"
#    TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS')}}"
#    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR')}}"
