Description: >
  Cloudfront distribution for UdaPeople.

Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String


Resources:
#  Needed for when we take the bucket private
#  CloudFrontOriginAccessIdentity:
#    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
#    Properties:
#      CloudFrontOriginAccessIdentityConfig:
#        Comment: Origin Access Identity for Serverless Static Website


  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "udapeople-${WorkflowID}.s3.amazonaws.com"
            Id: webpage
            S3OriginConfig:
              OriginAccessIdentity:
#              Needed for when we take the bucket private
#              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all

#  Needed for when we take the bucket private
#  BucketPolicy:
#    Type: AWS::S3::BucketPolicy
#    Properties:
#      Bucket: !Sub "udapeople-${WorkflowID}"
#      PolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#          - Effect: Allow
#            Principal:
#              AWS: !Sub 'arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}'
#            Action: 's3:GetObject'
#            Resource: !Sub 'arn:aws:s3:::udapeople-${WorkflowID}/*'

Outputs:
  WorkflowID:
    Value: !Sub ${WorkflowID}
    Description: URL for website hosted on S3
    Export:
      Name: WorkflowID
